function imageToGifConverter()
    % 创建主窗口
    fig = figure('Name', '图片转GIF转换器', ...
                 'Position', [100, 100, 600, 450], ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none', ...
                 'NumberTitle', 'off', ...
                 'Color', [0.95, 0.95, 0.95]);
    
    % 标题
    uicontrol('Style', 'text', ...
              'String', 'MATLAB 图片转GIF转换器', ...
              'Position', [150, 400, 300, 30], ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    % 文件夹选择部分
    uicontrol('Style', 'text', ...
              'String', '选择图片文件夹:', ...
              'Position', [50, 350, 120, 20], ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    folderPath = uicontrol('Style', 'edit', ...
                           'String', '', ...
                           'Position', [180, 350, 300, 25], ...
                           'BackgroundColor', 'white');
    
    uicontrol('Style', 'pushbutton', ...
              'String', '浏览...', ...
              'Position', [490, 350, 80, 25], ...
              'Callback', @browseFolder);
    
    % GIF参数设置
    uicontrol('Style', 'text', ...
              'String', 'GIF参数设置', ...
              'Position', [50, 300, 120, 20], ...
              'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    uicontrol('Style', 'text', ...
              'String', '帧延迟时间(秒):', ...
              'Position', [50, 270, 120, 20], ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    delayTime = uicontrol('Style', 'edit', ...
                          'String', '0.1', ...
                          'Position', [180, 270, 100, 25], ...
                          'BackgroundColor', 'white');
    
    uicontrol('Style', 'text', ...
              'String', '输出文件名:', ...
              'Position', [50, 240, 120, 20], ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    outputName = uicontrol('Style', 'edit', ...
                           'String', 'animation.gif', ...
                           'Position', [180, 240, 200, 25], ...
                           'BackgroundColor', 'white');
    
    % 文件类型选择
    uicontrol('Style', 'text', ...
              'String', '图片类型:', ...
              'Position', [50, 210, 120, 20], ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);
    
    fileTypes = {'*.jpg;*.jpeg;*.png;*.bmp;*.tif;*.tiff', '所有图片格式'; 
                 '*.jpg;*.jpeg', 'JPEG 图片';
                 '*.png', 'PNG 图片';
                 '*.bmp', 'BMP 图片';
                 '*.tif;*.tiff', 'TIFF 图片'};
    
    fileType = uicontrol('Style', 'popupmenu', ...
                         'String', {fileTypes{:,2}}, ...
                         'Position', [180, 210, 200, 25], ...
                         'BackgroundColor', 'white', ...
                         'UserData', {fileTypes{:,1}}, ...
                         'Value', 1);
    
    % 循环选项
    loopCount = uicontrol('Style', 'checkbox', ...
                          'String', '无限循环', ...
                          'Value', 1, ...
                          'Position', [180, 180, 100, 20], ...
                          'BackgroundColor', [0.95, 0.95, 0.95]);
    
    % 状态信息
    statusText = uicontrol('Style', 'text', ...
                           'String', '准备就绪', ...
                           'Position', [50, 120, 500, 30], ...
                           'HorizontalAlignment', 'left', ...
                           'BackgroundColor', [0.95, 0.95, 0.95]);
    
    % 创建GIF按钮
    uicontrol('Style', 'pushbutton', ...
              'String', '生成GIF动画', ...
              'Position', [200, 80, 200, 40], ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.4, 0.8, 0.4], ...
              'Callback', @createGif);
    
    % 浏览文件夹回调函数
    function browseFolder(~, ~)
        folder = uigetdir('', '选择包含图片的文件夹');
        if folder ~= 0
            set(folderPath, 'String', folder);
        end
    end

    % 创建GIF回调函数
    function createGif(~, ~)
        % 获取输入参数
        folder = get(folderPath, 'String');
        delay = str2double(get(delayTime, 'String'));
        outputFile = get(outputName, 'String');
        infiniteLoop = get(loopCount, 'Value');
        typeIndex = get(fileType, 'Value');
        filePatterns = get(fileType, 'UserData');
        filePattern = filePatterns{typeIndex};
        
        % 验证输入
        if isempty(folder) || ~isfolder(folder)
            set(statusText, 'String', '错误: 请选择有效的文件夹');
            return;
        end
        
        if isnan(delay) || delay <= 0
            set(statusText, 'String', '错误: 延迟时间必须为正数');
            return;
        end
        
        % 获取文件夹中的所有图片文件
        fileList = dir(fullfile(folder, '*.*'));
        imageFiles = {};
        for i = 1:length(fileList)
            [~, ~, ext] = fileparts(fileList(i).name);
            if ~fileList(i).isdir && any(strcmpi(ext, {'.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff'}))
                imageFiles{end+1} = fullfile(folder, fileList(i).name);
            end
        end
        
        if isempty(imageFiles)
            set(statusText, 'String', '错误: 文件夹中没有找到图片文件');
            return;
        end
        
        % 按文件名排序
        [~, sortedIdx] = sort({imageFiles{:}});
        imageFiles = imageFiles(sortedIdx);
        
        set(statusText, 'String', sprintf('找到 %d 张图片，正在生成GIF...', length(imageFiles)));
        drawnow;
        
        try
            % 创建GIF文件
            for i = 1:length(imageFiles)
                % 读取图片
                img = imread(imageFiles{i});
                
                % 如果是第一帧，创建GIF文件
                if i == 1
                    if infiniteLoop
                        loopValue = Inf;
                    else
                        loopValue = 1;
                    end
                    
                    imwrite(img, outputFile, 'gif', ...
                           'LoopCount', loopValue, ...
                           'DelayTime', delay);
                else
                    % 添加后续帧
                    imwrite(img, outputFile, 'gif', ...
                           'WriteMode', 'append', ...
                           'DelayTime', delay);
                end
                
                % 更新状态
                if mod(i, max(1, round(length(imageFiles)/10))) == 0
                    progress = round(i/length(imageFiles)*100);
                    set(statusText, 'String', sprintf('处理中: %d%% 完成 (%d/%d)', progress, i, length(imageFiles)));
                    drawnow;
                end
            end
            
            set(statusText, 'String', sprintf('成功创建GIF: %s', outputFile));
            
            % 显示生成的GIF
            try
                [imgData, cmap] = imread(outputFile, 'frames', 'all');
                if ~isempty(imgData)
                    figure('Name', '生成的GIF动画', 'NumberTitle', 'off');
                    imshow(imgData(:,:,:,1), cmap);
                    title(sprintf('GIF动画预览 (%d帧)', size(imgData,4)));
                end
            catch
                % 如果无法预览，忽略错误
            end
            
        catch e
            set(statusText, 'String', sprintf('错误: %s', e.message));
        end
    end
end